// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATpG0bi4og40WH-R9PhMSEvh0fbiECLBo',
    appId: '1:479405296471:web:235ec3ec7b2f68e6ad0c12',
    messagingSenderId: '479405296471',
    projectId: 'unipick-1b5ed',
    authDomain: 'unipick-1b5ed.firebaseapp.com',
    storageBucket: 'unipick-1b5ed.firebasestorage.app',
    measurementId: 'G-CJTCHBKTF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLs1JOPNjF9nL4Ou9PmeBB4gNhFmXgRec',
    appId: '1:479405296471:android:971a28f79600c226ad0c12',
    messagingSenderId: '479405296471',
    projectId: 'unipick-1b5ed',
    storageBucket: 'unipick-1b5ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi64QpRJrUSgThoQGrmIXc4b9KyfGPxqY',
    appId: '1:479405296471:ios:b5ec457bff91bb09ad0c12',
    messagingSenderId: '479405296471',
    projectId: 'unipick-1b5ed',
    storageBucket: 'unipick-1b5ed.firebasestorage.app',
    iosBundleId: 'com.example.testApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi64QpRJrUSgThoQGrmIXc4b9KyfGPxqY',
    appId: '1:479405296471:ios:b5ec457bff91bb09ad0c12',
    messagingSenderId: '479405296471',
    projectId: 'unipick-1b5ed',
    storageBucket: 'unipick-1b5ed.firebasestorage.app',
    iosBundleId: 'com.example.testApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATpG0bi4og40WH-R9PhMSEvh0fbiECLBo',
    appId: '1:479405296471:web:557d9d805ab55988ad0c12',
    messagingSenderId: '479405296471',
    projectId: 'unipick-1b5ed',
    authDomain: 'unipick-1b5ed.firebaseapp.com',
    storageBucket: 'unipick-1b5ed.firebasestorage.app',
    measurementId: 'G-8E7WZ0S5H2',
  );
}
